# -*- coding: utf-8 -*-
"""CreditCardTransactionDatasetOverview.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1G_bKqOm_zlDzsrwYcqEpC8XUHz8CmA8U
"""

import pandas as pd
from google.colab import files

uploaded = files.upload()

data = pd.read_csv("card_transdata.csv")

data.head()

data.tail()

data.info()

data.shape

data.describe()

data.columns

data.dtypes